- name: Run docker-compose
  hosts: localhost
  tasks:
    - name: Mensagem
      docker_service:
        project_name: Foca
        definition:
          version: "2"
          services:
            db:
              image: mysql:5.7
              volumes:
                - "{{playbook_dir}}/.data/db:/var/lib/mysql"
              environment:
                MYSQL_ROOT_PASSWORD: "{{pass}}"
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: "{{pass}}"

            wordpress:
              depends_on:
                - db
              image: wordpress:latest
              links:
                - db
              ports:
                - "8000:80"
              
              environment:
                WORDPRESS_DB_HOST: db:3306
                WORDPRESS_DB_PASSWORD: "{{pass}}"

